language: node_js
node_js:
  - "node"
branches:
  only:
  - master
  - develop
script:
  - npm install -g firebase-bolt
  - npm install -g firebase-tools
  - firebase-bolt database.rules.bolt
  - if [ $TRAVIS_BRANCH == "master" ]; then export FIREBASE_DEPLOY_KEY=$FIREBASE_DEPLOY_PROD_KEY; else FIREBASE_DEPLOY_KEY=$FIREBASE_DEPLOY_DEV_KEY; fi
  - if [ $TRAVIS_BRANCH == "master" ]; then export FIREBASE_PROJECT="production"; else export FIREBASE_PROJECT="development"; fi
  - firebase use $FIREBASE_PROJECT --token $FIREBASE_DEPLOY_KEY
  - firebase deploy -m "build $TRAVIS_BUILD_NUMBER $TRAVIS_BRANCH/$TRAVIS_COMMIT" --non-interactive --token $FIREBASE_DEPLOY_KEY
