language: node_js
node_js:
  - "node"
script:
  - npm install -g firebase-bolt
  - npm install -g firebase-tools
  - firebase-bolt rules.database.bolt
  - firebase deploy -m "Build $TRAVIS_BUILD_NUMBER" --non-interactive --token $FIREBASE_DEPLOY_KEY