language: node_js
node_js:
  - "node"
branches:
  only:
  - master
  - develop
script:
  - npm install -g firebase-bolt
  - npm install -g firebase-tools
  - firebase-bolt rules.database.bolt
  - if [ $TRAVIS_BRANCH == "master" ]; then export FIREBASE_DEPLOY_KEY=$FIREBASE_DEPLOY_PROD_KEY; else FIREBASE_DEPLOY_KEY=$FIREBASE_DEPLOY_DEV_KEY; fi
  - if [ $TRAVIS_BRANCH == "master" ]; then firebase use production; firebase use development; fi
  - firebase deploy -m "Commit $TRAVIS_BRANCH/$TRAVIS_COMMIT, travis build $TRAVIS_BUILD_NUMBER" --non-interactive --token $FIREBASE_DEPLOY_KEY
